### ISSUE TITLE
Notification Problem

### ISSUE THREAD

**Issue by diivyya** [Gourav-raj/Class-Reminder#1]
@Gourav-raj 
![WhatsApp Image 2021-02-03 at 19 14 04](https://user-images.githubusercontent.com/68610804/106755413-1cb76880-6654-11eb-8f91-f0d7c1b50fa9.jpeg)
The class reminder notification on discord is not up to date. It is giving reminder of a previously scheduled class.

**Comment by Gourav-raj** [comment]
Issue is resolved!!
